---
openapi: 3.0.3
info:
  title: quarkus-amylotool-predictor API
  version: 1.0-SNAPSHOT
tags:
  - name: predictions
paths:
  /api/prediction:
    post:
      tags:
        - predictions
      summary: Run predictions on sequences
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PredictionRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PredictionResult'
components:
  schemas:
    PredictionRequest:
      required:
        - sequences
      type: object
      properties:
        sequences:
          type: array
          items:
            type: string
        model:
          type: string
    PredictionResult:
      type: object
      properties:
        sequence:
          type: string
        maxIndex:
          format: int32
          type: integer
        score:
          format: float
          type: number
        withModel:
          format: int32
          type: integer
