version: '3.5'

services:

  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker:1.0.25
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    environment:
      AMQ_USER: quarkus
      AMQ_PASSWORD: quarkus
    networks:
      - amylotool-network

  quarkus-amylotool-orchestrator:
    image: chrisp/quarkus-amylotool-orchestrator:1.0-SNAPSHOT
    build:
      context: quarkus-amylotool-orchestrator
      dockerfile: src/main/docker/Dockerfile
    depends_on:
      - postgres
    environment:
      AMQP_HOST: artemis
      AMQP_PORT: 5672
      QA_PREDICTOR_URL: "http://quarkus-amylotool-predictor:8083"
      QA_ORCHESTRATOR_DB_USER: "qa_orchestrator"
      QA_ORCHESTRATOR_DB_PASSWORD: "qa_orchestrator"
      QA_ORCHESTRATOR_DB_URL: "jdbc:postgresql://postgres/qa_orchestrator"
    ports:
      - "8084:8084"
    networks:
      - amylotool-network

  quarkus-amylotool-predictor:
    image: chrisp/quarkus-amylotool-predictor:1.0-SNAPSHOT
    build:
      context: quarkus-amylotool-predictor
      dockerfile: src/main/docker/Dockerfile
    depends_on:
      - postgres
    environment:
      AMQP_HOST: artemis
      AMQP_PORT: 5672
      QA_PREDICTOR_DB_USER: "qa_predictor"
      QA_PREDICTOR_DB_PASSWORD: "qa_predictor"
      QA_PREDICTOR_DB_URL: "vertx-reactive:postgresql://postgres/qa_predictor"
      QA_PREDICTOR_MODELS_PATH: "/deployments/models/"
    ports:
      - "8083:8083"
    networks:
      - amylotool-network

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - amylotool-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@amylotool.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    networks:
      - amylotool-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pgdata:
  pgadmin-data:

networks:
  amylotool-network:
    name: amylotool