name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    - name: mvn clean package
      run: mvn --no-transfer-progress --batch-mode --errors clean package -Dmaven.test.skip=true
    - name: mvn clean verify
      run: mvn --no-transfer-progress --batch-mode --errors clean verify
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      env:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: chrispysz/quarkus-amylotool
